name: Hakyll site CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.8.3' ]
        cabal: [ '3.0' ]

    steps:
    - uses: actions/checkout@v2

    - name: Generate dotenv file
      run: |
        tee -a .env.secrets <<< "$DOTENV"
        if [[ -f .env.gpg ]]; then gpg --batch --yes --passphrase-fd 0 --output .env.decrypted --decrypt .env.gpg <<< "${{ secrets.GPG_PASSWORD }}"; fi
        grep -hs ^ .env.default .env.local .env .env.decrypted .env.secrets | tee .env.final
        echo "" >> .env.final
        owner="${{ github.repository_owner }}"
        repo="$(awk -F / '{print $2}' <<< "${{ github.repository }}")"
        if ! grep -qE '^BASEURL=' .env.final; then echo "BASEURL=${BASEURL:-https://$owner.github.io/$repo/}" | tee -a .env.final; fi
        if ! grep -qE '^DOMAIN=' .env.final; then echo "DOMAIN=$(awk -F / '/^BASEURL=/ {print $3}' .env.final | tail -n1)" | tee -a .env.final; fi
      env:
        DOTENV: ${{ secrets.DOTENV }}
        BASEURL: ${{ secrets.BASEURL }}

    - uses: c-py/action-dotenv-to-setenv@v2
      with:
        env-file: .env.final

    - uses: actions/cache@v1
      name: Cache ~/.npm
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - uses: actions/setup-node@v2
    - run: npm install

    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: cabal-store-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          cabal-store-${{ runner.OS }}-${{ matrix.ghc }}-
          cabal-store-${{ runner.OS }}-
    - name: Cache dist-newstyle
      uses: actions/cache@v1
      with:
        path: dist-newstyle
        key: dist-newstyle-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          dist-newstyle-${{ runner.OS }}-${{ matrix.ghc }}-
          dist-newstyle-${{ runner.OS }}-
    - name: Update the package list
      run: |
        cabal update
    - name: Build dependencies and the site generator
      run: |
        cabal build
    - name: Build the site
      env:
        LANG: en_US.UTF-8
      # build it two times to generate the correct metadata
      run: |
        cabal exec site -- build
        cabal exec site -- build
    - name: Check the site output
      run: |
        cabal exec site -- check

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        cname: '${{ env.DOMAIN }}'
        publish_branch: gh-pages
